ALTER TYPE "warranty_status" ADD VALUE IF NOT EXISTS 'TECHNICIAN_REPORTED_REPAIRED';
ALTER TYPE "warranty_status" ADD VALUE IF NOT EXISTS 'TECHNICIAN_REPORTED_UNREPAIRED';

ALTER TYPE "warranty_event_type" ADD VALUE IF NOT EXISTS 'TECHNICIAN_REPORTED_REPAIRED';
ALTER TYPE "warranty_event_type" ADD VALUE IF NOT EXISTS 'TECHNICIAN_REPORTED_UNREPAIRED';
