ALTER TYPE "warranty_status" ADD VALUE IF NOT EXISTS 'READY_FOR_CUSTOMER' AFTER 'RECEIVED_FROM_SUPPLIER';

ALTER TYPE "warranty_event_type" ADD VALUE IF NOT EXISTS 'READY_FOR_CUSTOMER' AFTER 'RECEIVED_FROM_SUPPLIER';
