"use client";
import Link from "next/link";
import { useState } from "react";
import { createWarrantyCases } from "@/modules/garantias/actions/warranty";

type Device = { imei: string; model: string; problem: string };
export function WarrantyIntakeForm() { const [clientName, setClientName] = useState(""); const [entryDate, setEntryDate] = useState(new Date().toLocaleDateString("en-CA", { timeZone: "America/Santo_Domingo" })); const [devices, setDevices] = useState<Device[]>([{ imei: "", model: "", problem: "" }]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); setMessage(""); const result = await createWarrantyCases({ clientName, entryDate, devices }); setBusy(false); setMessage(result.success ? `Ingreso creado: ${result.data.caseCodes.join(", ")}. Documento ${result.data.documentCode}.` : result.error); if (result.success) setDevices([{ imei: "", model: "", problem: "" }]); }
  return <form onSubmit={submit} className="mx-auto max-w-4xl space-y-5"><div className="enterprise-panel p-5"><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium text-[#344054]">Cliente<input required value={clientName} onChange={(e)=>setClientName(e.target.value)} className="mt-1 h-10 w-full rounded-lg border border-[#d0d5dd] px-3"/></label><label className="text-sm font-medium text-[#344054]">Fecha de ingreso<input type="date" required value={entryDate} onChange={(e)=>setEntryDate(e.target.value)} className="mt-1 h-10 w-full rounded-lg border border-[#d0d5dd] px-3"/></label></div></div><div className="enterprise-panel p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold text-[#101828]">Equipos</h2><p className="text-xs text-[#667085]">Cada IMEI genera un caso independiente.</p></div><button type="button" onClick={()=>setDevices([...devices, { imei:"", model:"", problem:"" }])} className="rounded-lg border border-indigo-200 px-3 py-2 text-xs font-semibold text-indigo-600">Agregar equipo</button></div><div className="space-y-4">{devices.map((device, index)=><div key={index} className="rounded-lg border border-[#e4e7ec] p-4"><div className="grid gap-3 md:grid-cols-[1fr_1fr_2fr_auto]"><input required maxLength={15} placeholder="IMEI (15 dígitos)" value={device.imei} onChange={(e)=>setDevices(devices.map((d,i)=>i===index?{...d,imei:e.target.value}:d))} className="h-10 rounded-lg border border-[#d0d5dd] px-3 text-sm"/><input required placeholder="Modelo" value={device.model} onChange={(e)=>setDevices(devices.map((d,i)=>i===index?{...d,model:e.target.value}:d))} className="h-10 rounded-lg border border-[#d0d5dd] px-3 text-sm"/><input required placeholder="Problema reportado" value={device.problem} onChange={(e)=>setDevices(devices.map((d,i)=>i===index?{...d,problem:e.target.value}:d))} className="h-10 rounded-lg border border-[#d0d5dd] px-3 text-sm"/>{devices.length>1&&<button type="button" onClick={()=>setDevices(devices.filter((_,i)=>i!==index))} className="text-xs text-red-600">Quitar</button>}</div></div>)}</div></div><div className="flex items-center justify-between"><Link href="/garantias" className="text-sm text-[#667085]">Cancelar</Link><button disabled={busy} className="rounded-lg bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy?"Guardando…":"Guardar ingreso"}</button></div>{message&&<p className="rounded-lg bg-indigo-50 p-3 text-sm text-indigo-800">{message}</p>}</form>; }
