"use client";
import { useState } from "react";
import { assignCasesToTechnician, deliverCasesToCustomer, markWarrantyCreditNote, receiveCasesFromSupplier, receiveCasesFromTechnician, sendCasesToSupplier } from "@/modules/garantias/actions/warranty";

type Row = { id: string; caseCode: string; imei: string; model: string; clientName: string; status: string };
const config = { assign: ["Entrega a técnico", "Técnico", "Selecciona casos recibidos"], receiveTech: ["Recepción del técnico", "Técnico", "Selecciona casos en reparación"], sendSupplier: ["Envío a suplidor", "Suplidor / marca", "Selecciona casos elegibles"], receiveSupplier: ["Recepción de suplidor", "Suplidor / marca", "Selecciona casos enviados"], deliver: ["Despacho al cliente", "Cliente", "Selecciona casos del mismo cliente"], credit: ["Nota de crédito", "", "Selecciona casos abiertos"] } as const;

export function WarrantyFlow({ operation, cases }: { operation: keyof typeof config; cases: Row[] }) {
  const [selected, setSelected] = useState<string[]>([]); const [counterparty, setCounterparty] = useState(""); const [reason, setReason] = useState(""); const [repaired, setRepaired] = useState(true); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [title, label, hint] = config[operation];
  async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); const input={caseCodes:selected,counterpartyName:counterparty,reason}; let result; if(operation === "assign") result=await assignCasesToTechnician(input); else if(operation === "receiveTech") result=await receiveCasesFromTechnician(input,repaired); else if(operation === "sendSupplier") result=await sendCasesToSupplier(input); else if(operation === "receiveSupplier") result=await receiveCasesFromSupplier(input); else if(operation === "deliver") result=await deliverCasesToCustomer(input); else result=await markWarrantyCreditNote(input); setBusy(false); const documentCode = result.success ? (result.data as { documentCode?: string }).documentCode : undefined; setMessage(result.success ? `Operación completada${documentCode ? `. Documento ${documentCode}.` : "."}` : result.error); if(result.success)setSelected([]); }
  return <form onSubmit={submit} className="enterprise-panel overflow-hidden"><div className="border-b border-[#e4e7ec] p-5"><h1 className="text-xl font-bold text-[#101828]">{title}</h1><p className="mt-1 text-sm text-[#667085]">{hint}. La confirmación se ejecuta en una sola transacción.</p></div>{operation !== "credit" && <div className="grid gap-4 border-b border-[#e4e7ec] p-5 md:grid-cols-2"><label className="text-sm font-medium text-[#344054]">{label}<input required value={counterparty} onChange={(e)=>setCounterparty(e.target.value)} className="mt-1 h-10 w-full rounded-lg border border-[#d0d5dd] px-3"/></label>{operation === "receiveTech" && <label className="flex items-center gap-2 self-end pb-2 text-sm"><input type="checkbox" checked={repaired} onChange={(e)=>setRepaired(e.target.checked)}/> Equipo reparado</label>}</div>}{(operation === "credit" || operation === "receiveTech" && !repaired) && <div className="border-b border-[#e4e7ec] p-5"><label className="text-sm font-medium text-[#344054]">Motivo<textarea required value={reason} onChange={(e)=>setReason(e.target.value)} className="mt-1 min-h-20 w-full rounded-lg border border-[#d0d5dd] p-3"/></label></div>}<div className="divide-y divide-[#f0f1f3]">{cases.map((item)=><label key={item.id} className="flex cursor-pointer items-center gap-3 p-4 hover:bg-[#f8fafc]"><input type="checkbox" checked={selected.includes(item.caseCode)} onChange={(e)=>setSelected(e.target.checked?[...selected,item.caseCode]:selected.filter((code)=>code!==item.caseCode))}/><span className="min-w-0 flex-1"><span className="font-mono text-xs font-bold text-indigo-600">{item.caseCode}</span><span className="ml-2 text-sm font-semibold text-[#344054]">{item.clientName} · {item.model}</span><span className="block font-mono text-xs text-[#667085]">{item.imei}</span></span></label>)}{cases.length===0&&<p className="p-8 text-center text-sm text-[#667085]">No hay casos elegibles para este flujo.</p>}</div><div className="flex items-center justify-between border-t border-[#e4e7ec] p-5"><span className="text-xs text-[#667085]">{selected.length} seleccionado(s)</span><button disabled={busy||selected.length===0} className="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy?"Procesando…":"Confirmar operación"}</button></div>{message&&<p className="m-5 rounded-lg bg-indigo-50 p-3 text-sm text-indigo-800">{message}</p>}</form>;
}
